### ISSUE TITLE
Over-midnight period

### ISSUE THREAD

**Issue by nlehuby** [Jungle-Bus/Busy-Hours#20]
I can't get working this use case: a night bus with the following schedule
![image](https://user-images.githubusercontent.com/919962/88566724-b4e5ec80-d036-11ea-81f4-a7395a5c95ec.png)
- from 21h50 to 1h20, every 35 min
- from 1h20 to 3h20, every hour
- from 3h20 to 6h50, every 35 min

The following form
![Screenshot_2020-07-27 Busy Hours(2)](https://user-images.githubusercontent.com/919962/88566944-11490c00-d037-11ea-9466-053b89be13ca.png)
is turned to that, when the page is reloaded (the over-midnight period is removed)
![Screenshot_2020-07-27 Busy Hours(3)](https://user-images.githubusercontent.com/919962/88566980-1efe9180-d037-11ea-86d5-9f382f9fd2b1.png)

And the following form, that cuts the over-midnight period into two regular periods, with start time < end time is ko too
![Screenshot_2020-07-27 Busy Hours](https://user-images.githubusercontent.com/919962/88566773-c929e980-d036-11ea-9a39-9e33f81d6da9.png)
turned into:
![Screenshot_2020-07-27 Busy Hours(1)](https://user-images.githubusercontent.com/919962/88566779-cc24da00-d036-11ea-83da-ab367e2975ce.png)

**Comment by nlehuby** [comment]
:thinking: maybe a parsing issue (in [transport-hours](https://github.com/Jungle-Bus/transport-hours-js)) actually
* in OSM: `opening_hours` = `Mo-Su,PH 01:20-06:45,21:50-01:20` https://www.openstreetmap.org/relation/2531207
* in Busy Hours: the 21:50 - 01:20 period is missing https://jungle-bus.github.io/Busy-Hours/#/line/2531207

**Comment by PanierAvide** [comment]
Right, there was an issue in transport-hours, I fixed it : https://github.com/Jungle-Bus/transport-hours-js/commit/dce31355fe721085a235956d0df48bac2e764bd7

You can update dependency and re-deploy, this should fix this issue.

**Comment by nlehuby** [comment]
thanks :+1: 

The python3 version is broken though: https://travis-ci.org/github/Jungle-Bus/transport-hours-py

**Comment by PanierAvide** [comment]
Fix for the fix :sweat_smile: https://github.com/Jungle-Bus/transport-hours-py/commit/a2653ff01f304af20decf0270cda3f355acffd92

**Comment by nlehuby** [comment]
:ok_hand: can you re-release it on pypi please ?

**Comment by PanierAvide** [comment]
Done

**Comment by nlehuby** [comment]
:thinking: I can still reproduce on the example below (https://www.openstreetmap.org/relation/2531207) with the last version of the lib - https://github.com/Jungle-Bus/Busy-Hours/commit/bec64cdbc1abe896dfe856679abd61937c82f6ad

and there is something wrong with the `npm install` on the deployment (I can't reproduce this error though): https://travis-ci.org/github/Jungle-Bus/Busy-Hours/builds/715464448

**Comment by nlehuby** [comment]
hum, the remaining issue seems to be the same as #24 (no interval exception on the before midnight part, so it is skipped)



opening_hours | Mo-Su,PH 01:20-06:45,21:50-01:20
-- | --
interval | 35
interval:conditional | 60 @ (Mo-Su,PH 01:20-03:20)

ends up as:
![image](https://user-images.githubusercontent.com/919962/153629662-5f344aa3-0837-4f90-8c4c-78992b2a0a66.png)
